### ISSUE TITLE
[Feature] Options to Render Hold with Jagged Edges

### ISSUE THREAD

**Issue by VVokos** [Yasu3D/MercuryMapper#11]
While the jagged hold effect is commonly used in Wacca, it might be good if there is a handy option, like the one we make Bezier holds. It is not an urgent function, but it's good to have it.
![Screenshot_2024-04-21-13-19-36-43_680d03679600f7af0b4c700c6b270fe7](https://github.com/Yasu3D/MercuryMapper/assets/59685862/b4fbc9ff-0c4c-42cd-816e-49949a194289)

**Comment by Yasu3D** [comment]
This feature was already planned, I'm still trying to figure out how I could make it user-friendly.

**Comment by Yasu3D** [comment]
implemented in upcoming release.
