### ISSUE TITLE
(Minor) Placing a R note hold causes subsequent hold placements to be (none)

### ISSUE THREAD

**Issue by ayhyap** [Yasu3D/MercuryMapper#2]
After placing a hold end with R note start, following hold starts placed are not R notes despite the UI setting remaining on R note.

Current workarounds: 
- select none type, then select R note type again.
- select different note type (e.g. touch), then select hold again.

**Comment by Yasu3D** [comment]
fixed in https://github.com/Yasu3D/MercuryMapper/releases/tag/v1.0.6
