### ISSUE TITLE
[1.0.4 Version]When pause preview and place a note, it won't be quantized.

### ISSUE THREAD

**Issue by traoearth** [Yasu3D/MercuryMapper#4]
Now:
![QQ截图20240324130602](https://github.com/Yasu3D/MercuryMapper/assets/82272385/9e0ca684-c8a2-4a1c-a2d8-7d133b2c9b37)

Should be:
![QQ截图20240324130621](https://github.com/Yasu3D/MercuryMapper/assets/82272385/880ce220-05f3-411b-88be-0ddea3d70d8f)

**Comment by Yasu3D** [comment]
Pausing during playback currently doesn't automatically quantize the current measure. It just pauses at the exact position the song was at. Will add an option to quantize on pause.

**Comment by Yasu3D** [comment]
fixed in https://github.com/Yasu3D/MercuryMapper/releases/tag/v1.0.6
