### ISSUE TITLE
[Major BUG]If a hold changed its width, the curve won't be smoothed IN ACTUAL PLAY.

### ISSUE THREAD

**Issue by traoearth** [Yasu3D/MercuryMapper#6]
![d8af69e37e976e76098f6806583afa0b](https://github.com/Yasu3D/MercuryMapper/assets/82272385/690351c0-2afe-4d70-bcea-431d387cf13a)

**Comment by Yasu3D** [comment]
Sadly can't fix this, at least not without a lot of headaches.

This happens only when using non-linear hold curves. If all segments were set to no-render, then it would look linear again.

The solution for now would be manually setting some of the segments to render and the rest to not render.

**Comment by Yasu3D** [comment]
Attempted a solution but it didn't really give good results. I'll close this for now, since tools in the upcoming release will make fixing this significantly easier.
