### ISSUE TITLE
Music Desync while editing

### ISSUE THREAD

**Issue by zabuzafreak** [Yasu3D/MercuryMapper#7]
While editing, when you rewind and playback a specific section the music does not match up with the proper measure. You have to rewind all the way to the beginning of the file.

**Comment by Yasu3D** [comment]
I have never encountered this issue before. If you have a video of it happening or steps to reproduce it, that would help.

**Comment by Yasu3D** [comment]
Closing for now, as there have been no other reports and this issue isn't reproducible.

**Comment by Speykious** [comment]
Here's a reproducible example: [jashin-no-wacca-zip](https://cdn.discordapp.com/attachments/956673889017151488/1297744148757090396/jashin-no-wacca.zip?ex=671709eb&is=6715b86b&hm=62cbc024aafda8b42ea9294612ec4504b9d9e0475dd3cac13a71169816ceb95b&)

To reproduce, try to start playing after the first time signature change and notice the desync happening.

After some testing, it seems that this problem only occurs when the audio is an mp3. If it's wav, flac or ogg, no desync happens.
